global:
	checkNewVersion: true
	sendAnonymousUsage: false

entryPoints:
	web:
		address: :80
	websecure:
		address: :443
providers:
	docker:
		exposedByDefault: false
	file: 
		directory: /etc/traefik
		watch: true
